more commit

diff --git a/fuzzers/inprocess/libfuzzer_libpng_launcher/Justfile b/fuzzers/inprocess/libfuzzer_libpng_launcher/Justfile
--- a/fuzzers/inprocess/libfuzzer_libpng_launcher/Justfile
+++ b/fuzzers/inprocess/libfuzzer_libpng_launcher/Justfile
@@ -188,12 +188,12 @@ test-tcp-fork: fuzzer-tcp
     rm -rf libafl_unix_shmem_server || true
     echo "Testing with TCP (fork)..."
     rm -rf out_tcp_fork || true
-    timeout 31s ./{{FUZZER_NAME}}-tcp --broker-port 21340 --cores 0 --input ./corpus --output ./out_tcp_fork --tcp --fork 2>&1 | tee fuzz_tcp_fork_stdout.log || true
-    if grep -qa "corpus: " fuzz_tcp_fork_stdout.log; then
+    timeout 31s ./{{FUZZER_NAME}}-tcp --broker-port 21340 --cores 0 --input ./corpus --output ./out_tcp_fork --tcp --fork > /dev/null 2>&1 || true
+    if [ -d "out_tcp_fork/default/queue" ]; then
         echo "Fuzzer (TCP fork) is working"
     else
-        echo "Fuzzer (TCP fork) does not generate any testcases or any crashes"
-        # exit 1
+        echo "Fuzzer (TCP fork) failed: queue directory not found"
+        exit 1
     fi
 
 [linux]
@@ -203,12 +203,12 @@ test-tcp-no-fork: fuzzer-tcp
     rm -rf libafl_unix_shmem_server || true
     echo "Testing with TCP (no fork)..."
     rm -rf out_tcp_no_fork || true
-    timeout 31s ./{{FUZZER_NAME}}-tcp --broker-port 21341 --cores 0 --input ./corpus --output ./out_tcp_no_fork --tcp 2>&1 | tee fuzz_tcp_no_fork_stdout.log || true
-    if grep -qa "corpus: " fuzz_tcp_no_fork_stdout.log; then
+    timeout 31s ./{{FUZZER_NAME}}-tcp --broker-port 21341 --cores 0 --input ./corpus --output ./out_tcp_no_fork --tcp > /dev/null 2>&1 || true
+    if [ -d "out_tcp_no_fork/default/queue" ]; then
         echo "Fuzzer (TCP no fork) is working"
     else
-        echo "Fuzzer (TCP no fork) does not generate any testcases or any crashes"
-        # exit 1
+        echo "Fuzzer (TCP no fork) failed: queue directory not found"
+        exit 1
     fi
 
 
