Some fixes

diff --git a/fuzzers/fuzzbench/Makefile b/fuzzers/fuzzbench/Makefile
--- a/fuzzers/fuzzbench/Makefile
+++ b/fuzzers/fuzzbench/Makefile
@@ -34,13 +34,14 @@ run: all
 short_test: all
 	mkdir in || true
 	echo a > in/a
-	timeout 11s ./$(FUZZER_NAME) out in
+	# Allow sigterm as exit code 
+	(timeout 11s ./$(FUZZER_NAME) out in || [ $$? -eq 124 ])
 	rm -rf out
 	rm -rf in
 
 test: all
 	mkdir in || true
 	echo a > in/a
-	timeout 60s ./$(FUZZER_NAME) out in
+	(timeout 60s ./$(FUZZER_NAME) out in || [ $$? -eq 124 ])
 	rm -rf out
 	rm -rf in
